# Generated by Django 5.1.7 on 2025-04-03 15:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('p', 'en attente'), ('r', 'rejecter'), ('a', 'approuver'), ('s', 'signaler'), ('d', 'desactivez')], default='p', max_length=1)),
                ('localisation', models.CharField(default='Akwa Soudanaise', max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-creer_le'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceFavoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Annonce favorie',
                'verbose_name_plural': 'Annonces Favories',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('un_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creer_le'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='medias/', verbose_name='Photo')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('envoyer_le', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('l', 'lu'), ('e', 'envoyé'), ('s', 'signalé'), ('r', 'recu')], default='e', max_length=1)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-envoyer_le'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_important', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('a', 'alerte'), ('c', 'critique'), ('d', 'default')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('duree_jours', models.SmallIntegerField(default=0)),
                ('statut', models.CharField(default='En attente', max_length=20)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
            },
        ),
        migrations.CreateModel(
            name='Tombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tombola_photos/')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cagnotte', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la cagnotte (FCFA)', max_digits=10)),
                ('participants_actuel', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('a', 'Active'), ('p', 'En attente'), ('f', 'Terminée'), ('r', 'rejeté')], default='p', max_length=1)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('statut', models.CharField(default='En attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
