# Generated by Django 5.2 on 2025-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('p', 'en attente'), ('r', 'rejecter'), ('a', 'approuver'), ('s', 'sponsorise'), ('d', 'desactivez')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='statut',
            field=models.CharField(choices=[('p', 'En attente'), ('a', 'approuver'), ('r', 'rejeter')], default='p', max_length=1),
        ),
    ]
