# Generated by Django 5.1.7 on 2025-03-13 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='note',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='annonce.media'),
        ),
    ]
