# Generated by Django 5.2 on 2025-05-20 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_alter_annonce_status_alter_publicite_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('terrain', 'Terrain'), ('maison', 'Maison'), ('appartement', 'Appartement'), ('local_commercial', 'Local Commercial'), ('autres', 'Autres')], max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=255)),
                ('superficie_min', models.PositiveIntegerField(help_text='Superficie minimale en m²')),
                ('superficie_max', models.PositiveIntegerField(help_text='Superficie maximale en m²')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitée')], default='en_attente', max_length=20)),
                ('frais', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de bien',
                'verbose_name_plural': 'Demandes de biens',
                'ordering': ['-date_creation'],
            },
        ),
    ]
