# Generated by Django 5.1.7 on 2025-03-16 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0004_remove_annonce_note_message_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-envoyer_le'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annonce.discussion'),
            preserve_default=False,
        ),
    ]
