# Generated by Django 5.2 on 2025-06-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0005_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
