# Generated by Django 5.1.7 on 2025-03-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0005_alter_message_options_remove_discussion_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='annonce.discussion'),
        ),
    ]
