# Generated by Django 5.1.7 on 2025-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0006_alter_message_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(default='Akwa Soudanaise', max_length=255),
        ),
    ]
