# Generated by Django 5.2 on 2025-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0006_usersubscription_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(default='en attente', max_length=20),
        ),
    ]
