# Generated by Django 5.1.7 on 2025-03-17 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0008_annonce_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-creer_le'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.RenameField(
            model_name='tombola',
            old_name='user',
            new_name='createur',
        ),
        migrations.RemoveField(
            model_name='tombola',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tombola',
            name='cagnotte',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la cagnotte (en euros, FCFA, etc.)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tombola',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tombola',
            name='participants_actuel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tombola',
            name='statut',
            field=models.CharField(choices=[('a', 'Active'), ('p', 'En attente'), ('f', 'Terminée')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='tombola',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tombola_photos/'),
        ),
        migrations.AlterField(
            model_name='tombola',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserTombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('tombola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.tombola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tombola')},
            },
        ),
        migrations.AddField(
            model_name='tombola',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tombolas', through='annonce.UserTombola', to=settings.AUTH_USER_MODEL),
        ),
    ]
