# Generated by Django 5.1.7 on 2025-03-18 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='creer_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
