# Generated by Django 5.1.7 on 2025-03-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0012_commentaire_creer_le'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='article',
            new_name='annonce',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'annonce')},
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='annonce.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'annonce')},
            },
        ),
    ]
