# Generated by Django 5.1.7 on 2025-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0013_rename_article_note_annonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
