# Generated by Django 5.1.7 on 2025-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0014_notification_is_archived_notification_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('a', 'alerte'), ('c', 'critique'), ('d', 'default')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
