# Generated by Django 5.1.7 on 2025-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0015_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('a', 'alerte'), ('c', 'critique'), ('d', 'default')], default='d', max_length=1),
        ),
    ]
