# Generated by Django 5.1.7 on 2025-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0017_alter_vue_annonce_publicite_vue_publicite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicite',
            options={'verbose_name': 'Publicité', 'verbose_name_plural': 'Publicités'},
        ),
        migrations.AddField(
            model_name='tombola',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tombola',
            name='cagnotte',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la cagnotte (FCFA)', max_digits=10),
        ),
    ]
