# Generated by Django 5.1.7 on 2025-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0019_rename_createur_tombola_creer_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombola',
            name='statut',
            field=models.CharField(choices=[('a', 'Active'), ('p', 'En attente'), ('f', 'Terminée'), ('r', 'rejeté')], default='p', max_length=1),
        ),
    ]
