# Generated by Django 5.1.7 on 2025-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0021_alter_discussion_options_alter_discussion_createur2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='un_read',
            field=models.BooleanField(default=False),
        ),
    ]
