# Generated by Django 5.1.7 on 2025-03-29 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0022_discussion_un_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='duree_jours',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicite',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicite',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tombola',
            name='creer_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usertombola',
            name='is_payed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertombola',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
