# Generated by Django 5.1.7 on 2025-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0023_publicite_duree_jours_publicite_is_payed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tombola',
            name='creer_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
