# Generated by Django 5.1.7 on 2025-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0024_publicite_statut_alter_tombola_creer_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertombola',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertombola',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
